### ISSUE TITLE
Build fails with Spec already loaded error

### ISSUE THREAD

**Issue by augustf** [concerto/concerto-debian#53]
We've had a couple of ideas about why the package build may have been failing, but none have panned out. The error I'm seeing in CircleCI is below, though I'm presently unable to replicate it locally.

Error details

    RuntimeError: Specs already loaded
      /var/lib/gems/1.9.1/gems/bundler-1.9.6/lib/bundler/definition.rb:118:in `resolve_remotely!'
      /var/lib/gems/1.9.1/gems/bundler-1.9.6/lib/bundler/installer.rb:79:in `run'
      /var/lib/gems/1.9.1/gems/bundler-1.9.6/lib/bundler/installer.rb:18:in `install'
      /var/lib/gems/1.9.1/gems/bundler-1.9.6/lib/bundler/cli/install.rb:80:in `run'
      /var/lib/gems/1.9.1/gems/bundler-1.9.6/lib/bundler/cli.rb:157:in `install'
      /var/lib/gems/1.9.1/gems/bundler-1.9.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /var/lib/gems/1.9.1/gems/bundler-1.9.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /var/lib/gems/1.9.1/gems/bundler-1.9.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /var/lib/gems/1.9.1/gems/bundler-1.9.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /var/lib/gems/1.9.1/gems/bundler-1.9.6/lib/bundler/cli.rb:10:in `start'
      /var/lib/gems/1.9.1/gems/bundler-1.9.6/bin/bundle:20:in `block in <top (required)>'
      /var/lib/gems/1.9.1/gems/bundler-1.9.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /var/lib/gems/1.9.1/gems/bundler-1.9.6/bin/bundle:18:in `<top (required)>'
      /usr/local/bin/bundle:23:in `load'
      /usr/local/bin/bundle:23:in `<main>'

**Comment by augustf** [comment]
Some searching through definition.rb suggests that the addition of the sudo command (and/or launching of a subshell) may be causing an environment issue that puts out the specs already loaded error. But I'm not any closer to reproducing the test environment conditions or resolving this.
